GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZHIuc3RyYW5nZSIsImlhdCI6MTY1MDM2NjA5NiwiZXhwIjoxNjUwMzY2MTA2fQ.pKo1GcnTSm9-fewyvy4nUOsieNXlmAMsZaiuX9fyaN0

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZHIuc3RyYW5nZSIsImlhdCI6MTY1MDM2NjM3Mn0.-Np9b657JywS6qUVlTiWJ2xGpZ8JAJHC0K0vPLUqwFQ"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZHIuc3RyYW5nZSIsImlhdCI6MTY1MDM2NjM3Mn0.-Np9b657JywS6qUVlTiWJ2xGpZ8JAJHC0K0vPLUqwFQ"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"dr.strange"
}